name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  golang-ci:
    uses: cccteam/github-workflows/.github/workflows/golang-ci.yml@7f103553e4cb3524d127299a6ac70d85156d36b3 # v7.0.0
    with:
      build-tags: '[""]'
      golangci-lint-version: "v2.11.4"
  semantic-titles:
    uses: cccteam/github-workflows/.github/workflows/semantic-pull-request-title.yml@7f103553e4cb3524d127299a6ac70d85156d36b3 # v7.0.0
